Inventory:RegisterItem("leatherjacket1", {
	Name			= "Кожаная куртка",
	Desc			= [[Кожанка тёмно-бежевого оттенка. Идёт в комплекте с джинсами, рюкзаком и ботинками. Популярна среди многих сталкеров-новичков]],
	Model			= "models/kek1ch/rookie_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/leatherjacket.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/bandit2.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	5,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	10,
			PsyDef	=	0,
			RadiationDef	=	0,
			BulletDef	=	10,
			ChemicalDef	=	10,
			ThermalDef	=	10,
			ElectricalDef	=	10,
			BlastDef	=	10,
				},
},
})

Inventory:RegisterItem("leatherjacket2", {
	Name			= "Аномальная кожанка",
	Desc			= [[Уникальный экземпляр кожаной куртки, получивший необычные свойства после попадания в аномалию «кисель».]],
	Model			= "models/kek1ch/rookie_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/leatherjacket.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/bandit4.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	5,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	10,
			PsyDef	=	0,
			RadiationDef	=	10,
			BulletDef	=	10,
			ChemicalDef	=	15,
			ThermalDef	=	15,
			ElectricalDef	=	15,
			BlastDef	=	10,
				},
},
})

Inventory:RegisterItem("bantitjacket1", {
	Name			= "Бандитская куртка",
	Desc			= [[Обычная непримечательная куртка из кожи. Носится новичками бандитов и ренегатами. По сути, почти никакой защиты не представляет в таком опасном месте как Зона. Но очень часто в неё вшивают броневые пластины, что повышает шанс спастись от пуль.]],
	Model			= "models/kek1ch/cs_rookie_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/chainmailjacket.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/bandit_backpack.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	5,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	10,
			PsyDef	=	0,
			RadiationDef	=	0,
			BulletDef	=	15,
			ChemicalDef	=	10,
			ThermalDef	=	10,
			ElectricalDef	=	10,
			BlastDef	=	10,
				},
},
})

Inventory:RegisterItem("bantitjacket2", {
	Name			= "Кольчужная куртка",
	Desc			= [[Уникальный экземпляр бандитской куртки. В подкладку вшито кольчужное полотно, за счёт чего повышена пулестойкость.]],
	Model			= "models/kek1ch/cs_rookie_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/chainmailjacket.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/bandit_backpack.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	5,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	15,
			PsyDef	=	0,
			RadiationDef	=	5,
			BulletDef	=	28,
			ChemicalDef	=	10,
			ThermalDef	=	10,
			ElectricalDef	=	10,
			BlastDef	=	15,
				},
},
})

Inventory:RegisterItem("naem1", {
	Name			= "Комбинезон наёмника",
	Desc			= [[Стандартный комбинезон наёмников. Представляет собой костюм из специальной ткани с усилениями в некоторых местах, разгрузочный жилет со множеством карманов и армейские берцы. Также, имеется сумка для противогаза и кобура для пистолета. Голова защищена лишь капюшоном, либо балаклавой (нередко совмещенной с американским экспериментальным противогазом XM40). На плече нашита эмблема наёмников — «синий орёл».]],
	Model			= "models/kek1ch/merc_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/naem.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/sunrise_merc.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	12,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	20,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	40,
			ChemicalDef	=	20,
			ThermalDef	=	30,
			ElectricalDef	=	30,
			BlastDef	=	35,
				},
},
})

Inventory:RegisterItem("naem2", {
	Name			= "Тяжелый бронекостюм Наемников",
	Desc			= [[Внешне тяжёлый бронекостюм напоминает экзоскелет, но первое и основное отличие, которое бросается в глаза, — это отсутствие сервоприводов на руках и ногах, а также аккумулятора за спиной]],
	Model			= "models/kek1ch/merc_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/tb_merc.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/rad_merc.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	12,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	60,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	70,
			ChemicalDef	=	20,
			ThermalDef	=	30,
			ElectricalDef	=	30,
			BlastDef	=	65,
				},
},
})

Inventory:RegisterItem("stalker1", {
	Name			= "Комбинезон «Заря»",
	Desc			= [[Основной комбинезон вольных сталкеров, встречается у одиночек с рангом «Опытный» и «Ветеран». Комбинезон носят с различными дополнениями в экипировке, т.к. каждый сталкер старается подогнать экипировку под себя. Может быть выборочно дополнен респиратором или противогазом, рюкзаком или баллонами с воздухом, отсюда и соответствующие внешние различия брони. Комплектуется берцами.]],
	Model			= "models/kek1ch/stalker_outfit.mdl",
	Weight			= 15,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/zarya01.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/SunriseNeutral_Masked.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	35,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	30,
			ChemicalDef	=	40,
			ThermalDef	=	40,
			ElectricalDef	=	40,
			BlastDef	=	30,
				},
},
})

Inventory:RegisterItem("stalker2", {
	Name			= 'Комбинезон "Газ"',
	Desc			= [[Этот костюм является улучшенной версией комбинезона «Заря». Изменилась его молекулярная структура из-за аномального воздействия, что привело к возникновению способности ускоренного заживления ран.]],
	Model			= "models/kek1ch/stalker_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/zarya02.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/sunrise_blak.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	50,
			PsyDef	=	5,
			RadiationDef	=	45,
			BulletDef	=	45,
			ChemicalDef	=	45,
			ThermalDef	=	45,
			ElectricalDef	=	45,
			BlastDef	=	35,
				},
},
})

Inventory:RegisterItem("stalker3", {
	Name			= "Комбинезон турист",
	Desc			= [[Бывший хозяин этой вещи был настоящим туристом, и, видать, не раз хаживал в тяжёлые, на грани человеческих возможностей походы. Он знал, как правильно распределить вес, который нёс и каким вещам отдать предпочтение. Карманы на куртке и грамотно подобранный рюкзак позволяют нести больший вес.]],
	Model			= "models/kek1ch/stalker_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/zarya05.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/sunrise_overwatch.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	25,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	45,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	45,
			ChemicalDef	=	40,
			ThermalDef	=	40,
			ElectricalDef	=	40,
			BlastDef	=	45,
				},
},
})

Inventory:RegisterItem("militay1", {
	Name			= "Бронекостюм «Берилл-5М»",
	Desc			= [[Бронекостюм, использующийся военными.Модифицированная для работы в условиях Зоны, экипировка армейского спецназа — Берилл-5М. В составе: средний армейский бронежилет, усиленный титановыми пластинами с бериллиевым покрытием двухслойный костюм и шлем Сфера-08. Неплохая защита от автоматных пуль и осколков на средних и дальних дистанциях.]],
	Model			= "models/kek1ch/spec_sold_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/berill5m.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/beri_mili.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	false,
		MaxWeight	=	18,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	20,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	45,
			ChemicalDef	=	30,
			ThermalDef	=	30,
			ElectricalDef	=	30,
			BlastDef	=	4,
				},
},
})

Inventory:RegisterItem("free1", {
	Name			= "Комбинезон «Ветер свободы»»",
	Desc			= [[Облегчённая версия костюма сталкера, производимая ремесленниками группировки «Свобода».]],
	Model			= "models/kek1ch/military_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/windoffreedom2.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/COPWindOfFreedom_reference.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	10,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	30,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	40,
			ChemicalDef	=	40,
			ThermalDef	=	30,
			ElectricalDef	=	40,
			BlastDef	=	35,
				},
},
})

Inventory:RegisterItem("free2", {
	Name			= "Комбез Свободы М2",
	Desc			= [[Уникальный образец комбинезона «Ветер свободы». комбинезон интегрирована металлическая сетка, что позволило значительно повысить защиту от электричества, а именно, от аномалии «электра». Защита повысилась на 40%, что в общей сумме даёт 90% — это прекрасный результат. Помимо этого, к комбинезону добавили ещё и ПНВ первого поколения, что также очень полезно.]],
	Model			= "models/kek1ch/svoboda_light_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/windoffreedom2.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/psz9d_free3.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	10,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	40,
			PsyDef	=	0,
			RadiationDef	=	50,
			BulletDef	=	40,
			ChemicalDef	=	40,
			ThermalDef	=	30,
			ElectricalDef	=	40,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("free3", {
	Name			= "Комбинезон «Страж свободы»",
	Desc			= [[Основная боевая экипировка группировки «Свобода».Производимый ремесленниками группировки «Свобода» усиленный комбинезон сталкера. Средний армейский бронежилет, плюс накладные усиливающие циркониевые элементы дают неплохую защиту от автоматных пуль и осколков на различных дистанциях. Материал костюма состоит из двух слоёв: специально обработанной кожи и ткани с асбестовой нитью. Даёт совсем малую защиту от различных аномальных воздействий и радиации.]],
	Model			= "models/chernobyl/outfit/freedom_b.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/windoffreedom.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/copfreedom_military.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	60,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	50,
			ChemicalDef	=	40,
			ThermalDef	=	40,
			ElectricalDef	=	40,
			BlastDef	=	45,
				},
},
})

Inventory:RegisterItem("mono1", {
	Name			= "Комбинезон «Монолита»",
	Desc			= [[Стандартный комбинезон, используемый группировкой «Монолит». Обычно его носят штурмовики, дозорные, либо разведчики.]],
	Model			= "models/kek1ch/monolith_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/monolit.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/monolith_vet.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	50,
			PsyDef	=	0,
			RadiationDef	=	50,
			BulletDef	=	40,
			ChemicalDef	=	50,
			ThermalDef	=	50,
			ElectricalDef	=	60,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("mono2", {
	Name			= "Модифицированный комбинезон «Монолита»",
	Desc			= [[Уникальный комбинезон «Монолита».Особенный образец монолитовской личной защиты. Изготовлен из более высокотехнологичного материала и дополненный экспериментальной пси-защитой. Его защитные характеристики превосходят некоторые армейские бронекостюмы, кроме того он способен противостоять пси-атакам.]],
	Model			= "models/kek1ch/monolith_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/monolit.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/monolith_vet.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	50,
			PsyDef	=	30,
			RadiationDef	=	50,
			BulletDef	=	40,
			ChemicalDef	=	50,
			ThermalDef	=	50,
			ElectricalDef	=	60,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("duty1", {
	Name			= "ПСЗ-9д «Броня Долга»",
	Desc			= [[Отличный бронекостюм, изготовленный ремесленниками группировки «Долг». Стандартная экипировка ветеранов-долговцев.Производится одним из оборонных киевских НИИ на заказ группировки «Долг». Простота и надежность базовой модели ПСЗ-9 в сочетании с новыми материалами предоставляет хорошую защиту от различных вредных воздействий, включая огнестрельные повреждения. Из-за отсутствия системы защиты дыхания бронежилет требует доработки.]],
	Model			= "models/kek1ch/dolg_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/ps39d.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/copduty_military.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	50,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	45,
			ChemicalDef	=	20,
			ThermalDef	=	20,
			ElectricalDef	=	20,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("duty4", {
	Name			= "ПСЗ-9д Усиленный",
	Desc			= [[Ранняя модель комбинезона «Долга» — бронежилет спецназа серии ПС3-9, приспособленный для использования в условиях Зоны. Способен защитить от автоматной пули, но очень громоздок и почти не обеспечивает защиту от аномальных воздействий. Установка контейнеров для артефактов не предусмотрена, зато возможно оснащение различными вспомогательными системами.]],
	Model			= "models/kek1ch/dolg_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/83.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/copdutybulat_reference.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	60,
			PsyDef	=	0,
			RadiationDef	=	60,
			BulletDef	=	60,
			ChemicalDef	=	40,
			ThermalDef	=	40,
			ElectricalDef	=	40,
			BlastDef	=	60,
				},
},
})

Inventory:RegisterItem("duty3", {
	Name			= "ПСЗ-9Мд «Универсальная защита»",
	Desc			= [[Комбинезон группировки «Долг», производимый на заказ Киевским НИИ. Является аналогом комбинезона «СЕВА», чаще всего используется долговцами-ветеранами.]],
	Model			= "models/kek1ch/dolg_scientific_outfit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/universalprotection.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/seva_duty.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	40,
			PsyDef	=	0,
			RadiationDef	=	50,
			BulletDef	=	40,
			ChemicalDef	=	50,
			ThermalDef	=	50,
			ElectricalDef	=	50,
			BlastDef	=	30,
				},
},
})

Inventory:RegisterItem("seva1", {
	Name			= "Комбинезон «СЕВА»",
	Desc			= [[Разработка одного из Киевских НИИ. Отлично защищает от аномального воздействия и радиации.Данный комбинезон предоставляет отличную альтернативу другим сталкеровским комбинезонам, изготовленным в кустарных условиях. Представляет систему дыхания с замкнутым циклом, а также встроенной системы подавления действия аномальных полей. За счет удачного подбора материалов является хорошим выбором. Единственный недостаток — его цена.]],
	Model			= "models/kek1ch/scientific_outfit_merc.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/seva.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/seva_urban.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	30,
			PsyDef	=	0,
			RadiationDef	=	55,
			BulletDef	=	40,
			ChemicalDef	=	50,
			ThermalDef	=	50,
			ElectricalDef	=	50,
			BlastDef	=	30,
				},
},
})

Inventory:RegisterItem("seva2", {
	Name			= "ССП-99 «Эколог»",
	Desc			= [[Стандартный комбинезон научных групп, действующих в Зоне.Созданный для работы в условиях Зоны костюм химической защиты ССП-99. Используется экспедициями учёных и сотрудничающих с ними сталкеров-экологов. Встроенная система фильтрации воздуха и кондиционирования. Не рассчитан на ведение боевых действий.]],
	Model			= "models/kek1ch/ecolog_outfit_orange.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/ecologist.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/ecologist.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	40,
			PsyDef	=	30,
			RadiationDef	=	70,
			BulletDef	=	20,
			ChemicalDef	=	70,
			ThermalDef	=	70,
			ElectricalDef	=	70,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("bulat", {
	Name			= "Бронекостюм «Булат»",
	Desc			= [[Усиленный бронекостюм военных с отличными показателями защиты, используется армейским спецназом. Комплектуется шлемом «Сфера М12».Армейский бронекостюм СКАТ-9М создан для проведения штурмовых операций в зонах активности аномалий. В составе: тяжёлый армейский бронекостюм серии ПСЗ-12п, встроенный компенсационный костюм, шлем Сфера-12М. Предоставляет великолепную защиту от пулевого и осколочного попадания, при этом не снижает подвижности солдата. В наличии сбалансированная система защиты от аномального воздействия.]],
	Model			= "models/kek1ch/stalker_comander_suit.mdl",
	Weight			= 5,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/bulat.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/copbulatblack_reference2.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	80,
			PsyDef	=	0,
			RadiationDef	=	70,
			BulletDef	=	55,
			ChemicalDef	=	50,
			ThermalDef	=	60,
			ElectricalDef	=	70,
			BlastDef	=	70,
				},
},
})

Inventory:RegisterItem("exo", {
	Name			= "Экзоскелет",
	Desc			= [[Экспериментальный образец военного экзоскелета. В серийное производство не пошёл ввиду чрезвычайно высокой себестоимости и некоторых огрехов в проектировании. Несмотря на это, из-за возможности значительно увеличивать мобильность носителя пользуется спросом и потому негласно выпускается малыми партиями за пределами Украины. Оснащён встроенным контейнером для артефактов.]],
	Model			= "models/chernobyl/outfit/lone_exo.mdl",
	Weight			= 15,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/exo.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/exo_lone.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	80,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	85,
			ChemicalDef	=	30,
			ThermalDef	=	30,
			ElectricalDef	=	30,
			BlastDef	=	80,
				},
},
})

Inventory:RegisterItem("exo_freedom", {
	Name			= "Экзоскелет 'Свобода'",
	Desc			= [[Модернизация обычного экзоскелета. Применение более лёгких материалов позволило снизить массу самого костюма, а также повысить его износоустойчивость.]],
	Model			= "models/kek1ch/freedom_exo_outfit.mdl",
	Weight			= 14,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/300.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/copfreedom_exosuit.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	80,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	85,
			ChemicalDef	=	30,
			ThermalDef	=	30,
			ElectricalDef	=	30,
			BlastDef	=	80,
				},
},
})

Inventory:RegisterItem("trenchsalkercoat", {
	Name			= "Кожаный Сталкерский плащ",
	Desc			= [[Обычный плащ из коричневой кожи. Заметной защиты носителю не обеспечивает. Разве что не даст замёрзнуть ночью и смягчит укус слепого пса. Довольно неудобен в условиях Зоны, но, тем не менее, часто используется бандитами — возможно, исключительно из-за внешнего вида.]],
	Model			= "models/chernobyl/outfit/bandit3.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/banditjacket.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/bandit_brown.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	false,
		MaxWeight	=	30,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	15,
			PsyDef	=	0,
			RadiationDef	=	0,
			BulletDef	=	30,
			ChemicalDef	=	15,
			ThermalDef	=	20,
			ElectricalDef	=	0,
			BlastDef	=	15,
				},
},
})

Inventory:RegisterItem("chn3a", {
	Name			= "Бронежилет ЧН-3а",
	Desc			= [[Некогда это была штатная экипировка штурмовых отрядов «Чистого неба». Уничтожение данной группировки стало доходчивым напоминанием о том, что даже отличное снаряжение не может гарантировать безопасность в Зоне. Данный защитный костюм способен не только остановить пистолетную пулю, но и обеспечивает хорошую защиту от аномальных воздействий. Оснащён встроенным контейнером для артефактов.]],
	Model			= "models/chernobyl/outfit/cs_light.mdl",
	Weight			= 11,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/chn3a.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/clearsky_heavyassault.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	40,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	50,
			ChemicalDef	=	20,
			ThermalDef	=	60,
			ElectricalDef	=	60,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("tacticalhelmet", {
	Name			= "Тактический шлем",
	Desc			= [[Западный образец тактического шлема, лишённый какой-либо маркировки. Предназначен для обеспечения командира подразделения максимальным количеством тактической информации при установке соответствующей электронной «начинки». Отличается усиленной конструкцией; кроме того, оснащён многослойной кевларовой защитой, респиратором и прибором ночного видения.]],
	Model			= "models/kek1ch/helm_battle.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/tacticalhelmet.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	1,
		Effects	=	{
			ChemicalDef	=	3,
			PsyDef	=	14,
			RadiationDef	=	2,
			BulletDef	=	21,
				},
},
})

Inventory:RegisterItem("sferam12", {
	Name			= "Шлем «Сфера М12»",
	Desc			= [[Отделанный тканью алюминиево-титановый шлем с карманами для стальных бронеэлементов и бронемаской. Обычно поставляется в комплекте с бронежилетами класса ПС3 для спецназа. Достаточно популярен в Зоне благодаря респиратору и встроенному прибору ночного видения, а также хорошей защите головы. Предусмотрена возможность установки электроники.]],
	Model			= "models/kek1ch/helm_battle.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/sferam12.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	1,
		Effects	=	{
			ChemicalDef	=	4,
			PsyDef	=	17,
			RadiationDef	=	2,
			BulletDef	=	22,
				},
},
})

Inventory:RegisterItem("antigas", {
	Name			= "Противогаз",
	Desc			= [[Стандартный противогаз, предназначенный для фильтрации из воздуха радиоактивной пыли и отравляющих веществ. Широко используется как новичками, так и ветеранами всех группировок ввиду своей функциональной незаменимости. Не оснащён защитой от пуль, осколков и механических воздействий.]],
	Model			= "models/kek1ch/helm_respirator.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/antigas.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	0,
		Effects	=	{
			ChemicalDef	=	9,
			PsyDef	=	7,
			RadiationDef	=	2,
			BulletDef	=	0,
				},
},
})

Inventory:RegisterItem("zaslon", {
	Name			= "Шлем «Заслон»",
	Desc			= [[Лёгкий шлем с герметичным забралом, предназначенный для защиты лица от некоторых аномальных воздействий. Судя по технологии, разработан тем же оборонным НИИ, что и комбинезон «СЕВА» — предположительно, для применения в комплекте с армейскими защитными костюмами.]],
	Model			= "models/kek1ch/helm_protective.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/zaslon.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	0,
		Effects	=	{
			ChemicalDef	=	9,
			PsyDef	=	21,
			RadiationDef	=	3,
			BulletDef	=	6,
				},
},
})

Inventory:RegisterItem("steelhelmet", {
	Name			= "Стальной шлем",
	Desc			= [[Стандартный армейский стальной шлем. Не обеспечивает защиту от аномалий или радиации, но способен отклонить прилетевшую по касательной пулю. Спросом в Зоне пользовался только в период первых столкновений между группировками.]],
	Model			= "models/kek1ch/helm_hardhat.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/steelhelmet.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	0,
		Effects	=	{
			ChemicalDef	=	0,
			PsyDef	=	14,
			RadiationDef	=	0,
			BulletDef	=	10,
				},
},
})

Inventory:RegisterItem("Ecologist1", {
	Name			= "Экзоскелет Наука-2",
	Desc			= [[Экзоскелет Наука-2 экспериментальная разработка Проффесора Сахарова объеденило в себе качества пулестойкого комбинезона и качества одного из самых практичных комбинезонов для изучения Зоны ССП-99]],
	Model			= "models/kek1ch/ecolog_outfit_green.mdl",
	Weight			= 16,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/ecolog_exo.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/exo_bean.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	30,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	60,
			PsyDef	=	20,
			RadiationDef	=	80,
			BulletDef	=	60,
			ChemicalDef	=	80,
			ThermalDef	=	80,
			ElectricalDef	=	80,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("Ecologist2", {
	Name			= "Комбинезон Восход",
	Desc			= [[Улучшенная версия комбинезона Заря, имеет увеличенную защиту от воздействий Аномальных и рдаиационных эффектов]],
	Model			= "models/chernobyl/outfit/sunrise.mdl",
	Weight			= 10,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/vosxod.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/compiled 0.34/SunriseEco_Masked.mdl",
	ArmorTable	=	{
		Containers	=	3,
		Helmet	=	true,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	40,
			PsyDef	=	10,
			RadiationDef	=	54,
			BulletDef	=	40,
			ChemicalDef	=	44,
			ThermalDef	=	44,
			ElectricalDef	=	44,
			BlastDef	=	30,
				},
},
})

Inventory:RegisterItem("Banditcloak", {
	Name			= "Укрепленный бандитский плащ",
	Desc			= [[Плащ коричневого цвета с надетым поверх кевларовым бронежилетом]],
	Model			= "models/chernobyl/outfit/bandit2.mdl",
	Weight			= 8,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/bandit.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/io7a_merc5.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	15,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	30,
			PsyDef	=	0,
			RadiationDef	=	20,
			BulletDef	=	40,
			ChemicalDef	=	20,
			ThermalDef	=	20,
			ElectricalDef	=	20,
			BlastDef	=	30,
				},
},
})

Inventory:RegisterItem("banditWorm", {
	Name			= "Комбинезон Червь",
	Desc			= [[Грубый комбинезон созданный в полевых условиях, используется авторитетными бандитами за свои защитные качества в бою]],
	Model			= "models/chernobyl/outfit/bandit2.mdl",
	Weight			= 10,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/veter_vot_odin_kostyumchik.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/bandit_starkovich.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	true,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	55,
			PsyDef	=	0,
			RadiationDef	=	25,
			BulletDef	=	56,
			ChemicalDef	=	20,
			ThermalDef	=	20,
			ElectricalDef	=	20,
			BlastDef	=	50,
				},
},
})

Inventory:RegisterItem("banditRaid", {
	Name			= "Комбинезон Рейдер",
	Desc			= [[Комбинезон Заря перекрашенный бандитами, легко заставит новичка попасть в ловушку]],
	Model			= "models/kek1ch/banditmerc_outfit.mdl",
	Weight			= 10,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/zarya05.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/sunrise_bandit1.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	true,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	55,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	50,
			ChemicalDef	=	36,
			ThermalDef	=	36,
			ElectricalDef	=	36,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("DolgOper", {
	Name			= "ПСД-10",
	Desc			= [[Бронекостюм Псд-10 был изготовлен на базе Бронекостюма Берилл-5м, используется оперативниками долга для проведения различных заданий в условиях аномальной или радиационной активности, что позволяет расширить поле боевых действий]],
	Model			= "models/chernobyl/outfit/dolg.mdl",
	Weight			= 15,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/pzs10d.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/psz9d_drk.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	24,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	65,
			PsyDef	=	0,
			RadiationDef	=	50,
			BulletDef	=	65,
			ChemicalDef	=	46,
			ThermalDef	=	46,
			ElectricalDef	=	46,
			BlastDef	=	50,
				},
},
})

Inventory:RegisterItem("Stalker1", {
	Name			= "Научный комбинезон Бандитов",
	Desc			= [[азработка одного из Киевских НИИ. Отлично защищает от аномального воздействия и радиации.Данный комбинезон предоставляет отличную альтернативу другим сталкеровским комбинезонам, изготовленным в кустарных условиях. Представляет систему дыхания с замкнутым циклом, а также встроенной системы подавления действия аномальных полей. За счет удачного подбора материалов является хорошим выбором. Единственный недостаток — его цена]],
	Model			= "models/kek1ch/scientific_outfit.mdl",
	Weight			= 13,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/seva.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/seva_vigilance.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	45,
			PsyDef	=	0,
			RadiationDef	=	35,
			BulletDef	=	55,
			ChemicalDef	=	40,
			ThermalDef	=	40,
			ElectricalDef	=	40,
			BlastDef	=	30,
				},
},
})

Inventory:RegisterItem("Stalker2", {
	Name			= "Бронекостюм Закат",
	Desc			= [[Модификация комбинезона Заря местными умельцами, Стальные и кевларовые вставки позволяют позволяют увеличить защищенность носителя]],
	Model			= "models/chernobyl/outfit/sunrise.mdl",
	Weight			= 13,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/brone_sunrise.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/sunrise_olive.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	25,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	55,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	65,
			ChemicalDef	=	36,
			ThermalDef	=	36,
			ElectricalDef	=	36,
			BlastDef	=	55,
				},
},
})

Inventory:RegisterItem("Stalker3", {
	Name			= "Комбинезон Смородина",
	Desc			= [[Модификация комбинезона Заря, веточки смородины вшитые в дополнительный слой ткани позволили носителю слится с местностью Зоны]],
	Model			= "models/chernobyl/outfit/sunrise.mdl",
	Weight			= 10,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/zarya04.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/sunrise_symmetry.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	44,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	50,
			ChemicalDef	=	36,
			ThermalDef	=	36,
			ElectricalDef	=	36,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("mercSeva1", {
	Name			= "Научный комбенизон Наемников",
	Desc			= [[Производимая в одном из киевских оборонных НИИ альтернатива кустарным комбинезонам сталкеров. Хотя встроенный бронежилет способен остановить только пистолетную пулю, система защиты от аномальных воздействий и радиации по праву считается непревзойдённой]],
	Model			= "models/kek1ch/scientific_outfit_merc.mdl",
	Weight			= 13,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/seva_merc.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/seva_merc.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	30,
			PsyDef	=	0,
			RadiationDef	=	50,
			BulletDef	=	40,
			ChemicalDef	=	50,
			ThermalDef	=	50,
			ElectricalDef	=	50,
			BlastDef	=	15,
				},
},
})

Inventory:RegisterItem("Merc1", {
	Name			= "Комбинезон Разведчика",
	Desc			= [[Легкий комбинезон окрашенный в песчанный камуфляж. В комплекте идет противогаз м4]],
	Model			= "models/kek1ch/merc_outfit.mdl",
	Weight			= 10,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/chn02.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/io7a_desert.mdl",
	ArmorTable	=	{
		Containers	=	3,
		Helmet	=	true,
		MaxWeight	=	20,
		Stamina	=	15,
		Effects	=	{
			ImpactDef	=	40,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	40,
			ChemicalDef	=	20,
			ThermalDef	=	20,
			ElectricalDef	=	20,
			BlastDef	=	20,
				},
},
})

Inventory:RegisterItem("Merc2", {
	Name			= "Бронекостюм Булат Наемников",
	Desc			= [[Укрепленная версия комбинезона Булат используемого спецназом ВСУ. Была сделана по заказу неизвестной организации для работы в зоне]],
	Model			= "models/kek1ch/stalker_comander_suit.mdl",
	Weight			= 15,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/bulat.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/skat_recondite.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	25,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	50,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	60,
			ChemicalDef	=	36,
			ThermalDef	=	36,
			ElectricalDef	=	36,
			BlastDef	=	50,
				},
},
})

Inventory:RegisterItem("Merc2", {
	Name			= "Бронекостюм Булат Наемников",
	Desc			= [[Укрепленная версия комбинезона Булат используемого спецназом ВСУ. Была сделана по заказу неизвестной организации для работы в зоне]],
	Model			= "models/kek1ch/stalker_comander_suit.mdl",
	Weight			= 15,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/bulat.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/skat_recondite.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	true,
		MaxWeight	=	25,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	50,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	60,
			ChemicalDef	=	36,
			ThermalDef	=	36,
			ElectricalDef	=	36,
			BlastDef	=	50,
				},
},
})

Inventory:RegisterItem("FreeTB1", {
	Name			= "Тяжелый бронекостюм Свободы",
	Desc			= [[Внешне тяжёлый бронекостюм напоминает экзоскелет, но первое и основное отличие, которое бросается в глаза, — это отсутствие сервоприводов на руках и ногах, а также аккумулятора за спиной]],
	Model			= "models/kek1ch/exolight_outfit.mdl",
	Weight			= 16,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/tb_merc.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/rad_free.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	25,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	60,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	70,
			ChemicalDef	=	46,
			ThermalDef	=	46,
			ElectricalDef	=	46,
			BlastDef	=	60,
				},
},
})

Inventory:RegisterItem("FreeSeva1", {
	Name			= "Научный комбинезон Свободы",
	Desc			= [[Комбинезон серии ПСЗ-9М, родственник серии «СЕВА», отличающийся от последних материалами на порядок хуже для условий Зоны Отчуждения. Производится кустарным способом в поселке Мирный, зачастую на такие ставят бывшие в употреблении «Заслоны»]],
	Model			= "models/chernobyl/outfit/free_seva.mdl",
	Weight			= 12,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/seva_svoboda.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/seva_free.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	18,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	30,
			PsyDef	=	0,
			RadiationDef	=	50,
			BulletDef	=	36,
			ChemicalDef	=	56,
			ThermalDef	=	56,
			ElectricalDef	=	56,
			BlastDef	=	20,
				},
},
})

Inventory:RegisterItem("FreeRE1", {
	Name			= "Бронекостюм Комменданта",
	Desc			= [[Комбинезон сталкера с усиленным бронежилетом, производимый ремесленниками группировки «Свобода», — удачное сочетание броневой и аномальной защит. Встроенный бронежилет из бронепластин и уложенного в несколько слоёв кевлара способен остановить пистолетную пулю. Для защиты от малых аномальных воздействий ткань костюма пропитана составом «Суверен».»]],
	Model			= "models/chernobyl/outfit/freedom_heavy.mdl",
	Weight			= 15,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/80.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/beri_free.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	true,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	55,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	65,
			ChemicalDef	=	40,
			ThermalDef	=	40,
			ElectricalDef	=	40,
			BlastDef	=	50,
				},
},
})

Inventory:RegisterItem("dolgexo1`", {
	Name			= "Экзоскелет Долга",
	Desc			= [[Отечественная разработка одного из НИИ специально для группировки «Долг». Боевые функции преобладают, большая грузоподъемность. Большой вес костюма однако не исключает возможность бегать в нем]],
	Model			= "models/chernobyl/outfit/dolg_exo.mdl",
	Weight			= 20,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/exo_dolg.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/duty_exo.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	45,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	85,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	85,
			ChemicalDef	=	30,
			ThermalDef	=	30,
			ElectricalDef	=	30,
			BlastDef	=	80,
				},
},
})

Inventory:RegisterItem("mercexo1`", {
	Name			= "Экзоскелет Наемников",
	Desc			= [[Экспериментальный образец военного экзоскелета западного производства. Данный экзоскелет относится к третьему поколению. Используется наёмниками. Упор сделан на боевое применение, аномальная устойчивость низкая. Режим бега активирован.]],
	Model			= "models/chernobyl/outfit/merc_exo.mdl",
	Weight			= 19,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/exo_merc.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/merc_exo.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	45,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	80,
			PsyDef	=	5,
			RadiationDef	=	45,
			BulletDef	=	85,
			ChemicalDef	=	35,
			ThermalDef	=	35,
			ElectricalDef	=	35,
			BlastDef	=	80,
				},
},
})

Inventory:RegisterItem("BanditTB1`", {
	Name			= "Тяжелый бронекостюм Бандитов",
	Desc			= [[Внешне тяжёлый бронекостюм напоминает экзоскелет, но первое и основное отличие, которое бросается в глаза, — это отсутствие сервоприводов на руках и ногах, а также аккумулятора за спиной.]],
	Model			= "models/kek1ch/exolight_outfit.mdl",
	Weight			= 19,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/tb_merc.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/rad_vigilance.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	false,
		MaxWeight	=	30,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	65,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	70,
			ChemicalDef	=	35,
			ThermalDef	=	35,
			ElectricalDef	=	35,
			BlastDef	=	60,
				},
},
})

Inventory:RegisterItem("Banditexo", {
	Name			= "Экзоскелет бандитов",
	Desc			= [[Экспериментальный образец военного экзоскелета. В серийное производство не пошёл ввиду чрезвычайно высокой себестоимости и некоторых огрехов в проектировании. Несмотря на это, из-за возможности значительно увеличивать мобильность носителя пользуется спросом и потому негласно выпускается малыми партиями за пределами Украины. Оснащён встроенным контейнером для артефактов.]],
	Model			= "models/kek1ch/bandit_exo_outfit.mdl",
	Weight			= 19,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/exo_bandit.png",
	IsArmor			= true,
	ArmorModel			= "models/exoskelet/exo.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	30,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	75,
			PsyDef	=	0,
			RadiationDef	=	40,
			BulletDef	=	80,
			ChemicalDef	=	40,
			ThermalDef	=	40,
			ElectricalDef	=	40,
			BlastDef	=	75,
				},
},
})

Inventory:RegisterItem("DOLGTB1", {
	Name			= "Тяжелый бронекостюм Долга",
	Desc			= [[Внешне тяжёлый бронекостюм напоминает экзоскелет, но первое и основное отличие, которое бросается в глаза, — это отсутствие сервоприводов на руках и ногах, а также аккумулятора за спиной]],
	Model			= "models/kek1ch/exolight_outfit.mdl",
	Weight			= 18,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/tb_merc.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/rad_duty.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	25,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	60,
			PsyDef	=	0,
			RadiationDef	=	37,
			BulletDef	=	75,
			ChemicalDef	=	34,
			ThermalDef	=	34,
			ElectricalDef	=	34,
			BlastDef	=	60,
				},
},
})

Inventory:RegisterItem("SunriseTB1", {
	Name			= "Тяжелый бронекостюм",
	Desc			= [[Внешне тяжёлый бронекостюм напоминает экзоскелет, но первое и основное отличие, которое бросается в глаза, — это отсутствие сервоприводов на руках и ногах, а также аккумулятора за спиной]],
	Model			= "models/kek1ch/exolight_outfit.mdl",
	Weight			= 18,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/tb_merc.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/rad_lone.mdl",
	ArmorTable	=	{
		Containers	=	1,
		Helmet	=	false,
		MaxWeight	=	25,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	60,
			PsyDef	=	0,
			RadiationDef	=	37,
			BulletDef	=	75,
			ChemicalDef	=	34,
			ThermalDef	=	34,
			ElectricalDef	=	34,
			BlastDef	=	60,
				},
},
})

Inventory:RegisterItem("duty2", {
	Name			= "ПС5-М Монстробой",
	Desc			= [[Уникальная версия комбинезона ПСЗ-9д «Броня Долга».Долговский бронекостюм с улучшенной защитой от укусов и порезов.]],
	Model			= "models/kek1ch/dolg_outfit.mdl",
	Weight			= 9,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/dolg_monstroboy.png",
	IsArmor			= true,
	ArmorModel			= "models/stalkertnb/psz9d_duty4.mdl",
	ArmorTable	=	{
		Containers	=	2,
		Helmet	=	false,
		MaxWeight	=	20,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	65,
			PsyDef	=	0,
			RadiationDef	=	30,
			BulletDef	=	50,
			ChemicalDef	=	30,
			ThermalDef	=	30,
			ElectricalDef	=	30,
			BlastDef	=	40,
				},
},
})

Inventory:RegisterItem("trenchcoat", {
	Name			= "Кожаный Бандитский плащ",
	Desc			= [[Обычный плащ из чёрной кожи. Заметной защиты носителю не обеспечивает. Разве что не даст замёрзнуть ночью и смягчит укус слепого пса. Довольно неудобен в условиях Зоны, но, тем не менее, часто используется бандитами — возможно, исключительно из-за внешнего вида.]],
	Model			= "models/chernobyl/outfit/bandit3a.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 2,
	SizeY			= 2,
	IconMat			= "icons/armor/banditjacket.png",
	IsArmor			= true,
	ArmorModel			= "models/player/stalker/bandit_black.mdl",
	ArmorTable	=	{
		Containers	=	0,
		Helmet	=	false,
		MaxWeight	=	30,
		Stamina	=	0,
		Effects	=	{
			ImpactDef	=	15,
			PsyDef	=	0,
			RadiationDef	=	0,
			BulletDef	=	30,
			ChemicalDef	=	15,
			ThermalDef	=	20,
			ElectricalDef	=	0,
			BlastDef	=	15,
				},
},
})

Inventory:RegisterItem("psishlem", {
	Name			= "Пси-шлем»",
	Desc			= [[Настроенный прототип, разработанный учёными для защиты от пси-излучения.]],
	Model			= "models/kek1ch/item_psi_helmet.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/psiprotector.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	0,
		Effects	=	{
			ChemicalDef	=	0,
			PsyDef	=	60,
			RadiationDef	=	5,
			BulletDef	=	5,
				},
},
})

Inventory:RegisterItem("tacticaldolghelmet", {
	Name			= "Тактический шлем Долга",
	Desc			= [[Западный образец тактического шлема, Маркирован эмблемой Долга. Предназначен для обеспечения бойца подразделения максимальным количеством тактической информации при установке соответствующей электронной «начинки». Отличается усиленной конструкцией; кроме того, оснащён многослойной кевларовой защитой, респиратором и прибором ночного видения.]],
	Model			= "models/chernobyl/outfit/dolg_battlehelm.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/tacticalhelmet.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	1,
		Effects	=	{
			ChemicalDef	=	3,
			PsyDef	=	10,
			RadiationDef	=	2,
			BulletDef	=	31,
				},
},
})

Inventory:RegisterItem("tacticalfreedomhelmet", {
	Name			= "Шлем Свободы",
	Desc			= [[Западный образец тактического шлема, Маркирован эмблемой Свободы. Предназначен для обеспечения бойца подразделения максимальным количеством тактической информации при установке соответствующей электронной «начинки». Отличается усиленной конструкцией; кроме того, оснащён многослойной кевларовой защитой, респиратором и прибором ночного видения.]],
	Model			= "models/chernobyl/outfit/free_tactichelm.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/tacticalhelmet.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	1,
		Effects	=	{
			ChemicalDef	=	3,
			PsyDef	=	10,
			RadiationDef	=	2,
			BulletDef	=	31,
				},
},
})

Inventory:RegisterItem("antigasm40", {
	Name			= "Противогаз М40 НАТО",
	Desc			= [[Улучшенный противогаз, предназначенный для фильтрации из воздуха радиоактивной пыли и отравляющих веществ.]],
	Model			= "models/kek1ch/helm_m40.mdl",
	Weight			= 4,
	Category			= "Armor",
	SizeX			= 1,
	SizeY			= 1,
	IconMat			= "icons/armor/antigas.png",
	IsHelmet			= true,
	HelmetTable	=	{
		NVD	=	1,
		Effects	=	{
			ChemicalDef	=	9,
			PsyDef	=	5,
			RadiationDef	=	8,
			BulletDef	=	10,
				},
},
})

